export const api = {
  SERVER: 'http://192.168.1.106:8000/api/v1/',
  LOGIN: 'login',
  REGISTER: 'register',
  LOGOUT: 'logout',
  LIKE: 'like',
  UNLIKE: 'unlike',
  SAVE: 'save',
  UNSAVE: 'unsave',
  COMMENT: 'comment',
  UNCOMMENT: 'uncomment',
  RACE: 'race',
  LATESTPETS: 'pets-latest',
  LATESTPETFILTER: 'pets-latest/filter=',
  PET: 'pet',
  ADDPET: 'add-pet',
  GETADDPET: 'get-add-pet',
  GETEDITPET: 'edit-pet',
  UPDATEPET: 'update-pet',
  DELETEPET: 'delete-pet',
  MYPETS: 'my-pets',
  SAVEDLIST: 'saved-list',
  SHOWMYPROFILE: 'showMyProfile',
  GETPROFILEEDIT: 'profile-edit-get',
  GETMYPROFILE: 'showMyProfile',
  UPDATEPROFILE: 'profile-edit-update',
  SEARCH: 'search?&keyword=',

}

  