export const icons = {
  HOME: require('@assets/icons/menu/home.png'),
  CHAT: require('@assets/icons/menu/chat.png'),
  FAVORITE: require('@assets/icons/menu/fav.png'),
  ADDPET: require('@assets/icons/menu/add.png'),
  PROFILE: require('@assets/icons/menu/profile.png'),
  SEARCHMENU: require('@assets/icons/menu/search.png'),
  LOGO: require('@assets/icons/logo.png'),
  CATLOGIN: require('@assets/icons/catLogin.png'),
  LOCATION: require('@assets/icons/location.png'),
  DOGIMG: require('@assets/icons/pets/dog.png'),
  CATIMG: require('@assets/icons/pets/cat.png'),
  LIKE1: require('@assets/icons/like1.png'),
  LIKE2: require('@assets/icons/like2.png'),
  SEARCH: require('@assets/icons/search.png'),
  FILTER: require('@assets/icons/filter.png'),
  FILTER1: require('@assets/icons/filter1.png'),
  BACK: require('@assets/icons/back.png'),
  PHONE: require('@assets/icons/phone.png'),
  CALL: require('@assets/icons/call.png'),
  CROSS: require('@assets/icons/cross.png'),
  HAMBURGER: require('@assets/icons/hamburger.png'),

  CATFILTER: require('@assets/icons/pet_icons/cat.png'),
  DOGFILTER: require('@assets/icons/pet_icons/dog2.png'),
  FISHFILTER: require('@assets/icons/pet_icons/fish.png'),
  BIRDFILTER: require('@assets/icons/pet_icons/bird.png'),
  HAMSTERFILTER: require('@assets/icons/pet_icons/hamster.png'),
  HORSEFILTER: require('@assets/icons/pet_icons/horse.png'),
  FARMFILTER: require('@assets/icons/pet_icons/farm.png'),
}