export const routes = {
  HOME: 'home',
  CHAT: 'chat',
  FAVORITE: 'favorite',
  ADDPET: 'addpet',
  PROFILE: 'profile',
  ADDNAVIGATION: 'add_navigation',
  PREVIEWPET: 'preview_pet',
  EDITPET: 'edit_pet',
  VIEWPET: 'view_pet',
  REGISTER: 'register',
  LOGIN: 'login',
  SHOWMYPROFILE: 'show_my_profile',
  EDITPROFILE: 'edit_profile',
  SHOWPET: 'show_pet',
  SEARCH: 'search',
  SHOWPROFILE: 'show_profile',
  MESSAGELIST: 'messages_list',
  MESSAGE: 'message',
  m1: 'm1',
  m2: 'm2',
  m3: 'm3',
  m4: 'm4',
  m5: 'm5',
  MENU: 'menu',
  AUTH: 'auth',
  OPTIONS: 'options',
  SAVED: 'saved',
  SHOPS: 'shops',
  NAMEGEN: 'name_generator',
  OPTIONLIST: 'Option List'
}